### ISSUE TITLE
404 when trying to see the Challenges from Kitt

### ISSUE THREAD

**Issue by AlvaroPata** [lewagon/react-giphy#6]
I was trying to go through the challenges on Kitt but when I click on them I get a 404 on GitHub...

**Comment by Eschults** [comment]
Hello @AlvaroPata 👋 
Thank you for raising this 🙏 
You should now have access to the track's repo 👉 [lewagon/react-redux-challenges](https://github.com/lewagon/react-redux-challenges) 👌 

Enjoy 🚀
